teams:
  - name: bots
    maintainers:
      - hyperledger-bot
  - name: identus-admins
    maintainers:
      - yshyn-iohk
    members:
      - FabioPinheiro
      - amagyar-iohk
      - elribonazo
      - goncalo-frade-iohk
      - curtis-h
      - mineme0110
  - name: identus-maintainers
    maintainers:
      - yshyn-iohk
    members:
      - EzequielPostan
      - FabioPinheiro
      - FayyaadhAdams
      - amagyar-iohk
      - bsandmann
      - curtis-h
      - elribonazo
      - goncalo-frade-iohk
      - jesusdiazvico
      - mineme0110
      - patlo-iog
  - name: staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - thelinuxfoundation
repositories:
  - name: apollo
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: cloud-agent
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: docs
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: edge-agent-sdk-kmp
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: edge-agent-sdk-swift
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: edge-agent-sdk-ts
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: governance
    teams:
      identus-admins: maintain
      staff: maintain
    visibility: public
  - name: identus
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: infrastructure
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: private
  - name: keycloak-plugins
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: mediator
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: vdr
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
