teams:
  - name: bots
    maintainers:
      - hyperledger-bot
  - name: identus-admins
    maintainers:
      - yshyn-iohk
    members:
      - FabioPinheiro
      - amagyar-iohk
      - elribonazo
      - goncalo-frade-iohk
      - curtis-h
      - mineme0110
      - patextreme
  - name: identus-maintainers
    maintainers:
      - yshyn-iohk
    members:
      - FabioPinheiro
      - amagyar-iohk
      - bsandmann
      - curtis-h
      - elribonazo
      - goncalo-frade-iohk
      - jesusdiazvico
      - mineme0110
      - patextreme
      - robertocarvajal
      - coveloper
      - bsandmann
      - Yummy-Yums
  - name: staff
    maintainers:
      - ryjones
    members:
      - jwagantall
      - thelinuxfoundation
repositories:
  - name: apollo
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: cloud-agent
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: docs
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: sdk-kmp
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: sdk-swift
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: sdk-ts
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: governance
    teams:
      identus-admins: maintain
      staff: maintain
    visibility: public
  - name: .github
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: hyperledger-identus
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: infrastructure
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: private
  - name: keycloak-plugins
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: mediator
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: vdr
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: integration
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
  - name: neoprism
    teams:
      bots: admin
      identus-admins: admin
      identus-maintainers: maintain
    visibility: public
