teams:
    - name: identus-admins
      maintainers:
        - yshyn-iohk
      members:
        - FabioPinheiro
        - amagyar-iohk
        - elribonazo
    - name: identus-maintainers
      maintainers:
        - yshyn-iohk
      members:
        - EzequielPostan
        - FabioPinheiro
        - FayyaadhAdams
        - amagyar-iohk
        - bsandmann
        - curtis-h
        - elribonazo
        - goncalo-frade-iohk
        - jesusdiazvico
        - mineme0110
        - patlo-iog
    - name: staff
      maintainers:
        - ryjones
      members:
        - jwagantall
        - thelinuxfoundation
repositories:
    - name: governance
      teams:
        identus-admins: maintain
        staff: maintain
      visibility: public
    - name: mediator
      teams:
        identus-admins: admin
        identus-maintainers: maintain
      visibility: public
