teams:
    - name: identus-admins
      maintainers:
        - ryjones
      members:
        - yshyn-iohk
#      members:
        - FabioPinheiro
        - amagyar-iohk
        - elribonazo
    - name: identus-maintainers
      maintainers:
        - ryjones
      members:
        - yshyn-iohk
#      members:
        - CryptoKnightIOG
        - DannieBGoode
        - EzequielPostan
        - FabioPinheiro
        - FayyaadhAdams
        - amagyar-iohk
        - blockchaintimothy
        - bsandmann
        - bvoiturier
        - cristianIOHK
        - curtis-h
        - elribonazo
        - essbante-io
        - goncalo-frade-iohk
        - jesusdiazvico
        - mattklepp
        - milosbackonja
        - milosh86
        - mineme0110
        - mkbreuningIOHK
        - patlo-iog
        - petevielhaber
        - shotexa
        - urosmrvic-iohk
        - womfoo
    - name: staff
      maintainers:
        - ryjones
      members:
        - jwagantall
        - thelinuxfoundation
repositories:
    - name: governance
      teams:
        staff: maintain
      visibility: public
